services:
  btxl:
    image: ${BTXL_IMAGE:-ghcr.io/hajimilvdou/btxl:latest}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        COMMIT: ${COMMIT:-none}
        BUILD_DATE: ${BUILD_DATE:-unknown}
    container_name: btxl
    # env_file:
    #   - .env
    environment:
      DEPLOY: ${DEPLOY:-}
    ports:
      - "8317:8317"
    volumes:
      - ${BTXL_CONFIG_PATH:-./config.yaml}:/opt/btxl/config.yaml
      - ${BTXL_AUTH_PATH:-./auths}:/root/.btxl
      - ${BTXL_LOG_PATH:-./logs}:/opt/btxl/logs
    restart: unless-stopped
